apiVersion: v1
kind: Namespace
metadata:
  name: demo-cluster


---
apiVersion: bocloud.io/v1beta1
kind: MetalNode
metadata:
  name: metalnode-centos-148
  namespace: demo-cluster
spec:
  # TODO(user): Add fields here
  nodeName: centos-148
  nodeEndPoint:
    host: 10.20.9.148
    sshAuth:
      user: centos
      password: Ccc51521!
      port: 22
#  initializationCmd:
#    cmds:
#      - "echo hello world"

---
apiVersion: bocloud.io/v1beta1
kind: MetalNode
metadata:
  name: metalnode-centos-147
  namespace: demo-cluster
spec:
  # TODO(user): Add fields here
  nodeName: centos-147
  nodeEndPoint:
    host: 10.20.9.147
    sshAuth:
      user: centos
      password: Ccc51521!
      port: 22
#  initializationCmd:
#    cmds:
#      - "echo hello world"

