apiVersion: metal.metal.node/v1beta1
kind: MetalNode
metadata:
  name: metalnode-centos-147
spec:
  # TODO(user): Add fields here
  nodeName: centos-147
  nodeEndPoint:
    host: 10.20.9.147
    sshAuth:
      user: centos
      password: Ccc51521!
      port: 22
#  initializationCmd:
#    cmds:
#      - "echo hello world"

